CREATE TABLE tasks ( 
id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT 
, user VARCHAR(254) NOT NULL 
, email VARCHAR(254) NOT NULL 
, task VARCHAR(254) NOT NULL 
, status VARCHAR(254) NULL 
, notes VARCHAR(254) NULL 
, PRIMARY KEY (id)
) 
ENGINE = InnoDB; 